name: Rust

on:
  push:
    branches: [ "pythia" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Benchmark
      run: cargo run -p aptos-forge-cli --release -- --suite "local_test_suite" --num-validators 4 test local-swarm
